name    'coldfrontlabs-drush'
version '0.1.0'
source 'https://github.com/coldfrontlabs/coldfrontlabs-drush'
author 'Coldfront Labs Inc.'
license 'GPL, Version 2.0'
summary 'Manage Drush with Puppet'
description 'Install Drush and execute Drush commands with Puppet.'
project_page 'https://github.com/coldfrontlabs/coldfrontlabs-drush'

dependency 'tPl0ch/composer', '>= 1.2.1'
dependency 'stahnma/epel', '>= 0.0.6'
