name    'coldfront-drush'
version '0.1.0'
source 'UNKNOWN'
author 'coldfront'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

dependency 'tPl0ch/composer', '>= 1.2.1'